updated deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,15 +46,15 @@ jobs:
           echo "Waiting 15s for container to boot..."
           sleep 15
 
-          echo "Checking if container is healthy..."
-          if curl -f http://localhost:80 > /dev/null 2>&1; then
-            echo " New container is healthy. Updating stable tag."
-            docker tag $IMAGE $STABLE
-            docker push $STABLE
-          else
-            echo " New container failed. Rolling back to stable."
-            docker stop nextjs-app || true
-            docker rm nextjs-app || true
-            docker pull $STABLE
-            docker run -d -p 80:3000 --name nextjs-app $STABLE
-          fi
+      # echo "Checking if container is healthy..."
+      # if curl -f http://localhost:80 > /dev/null 2>&1; then
+      #   echo " New container is healthy. Updating stable tag."
+      #   docker tag $IMAGE $STABLE
+      #   docker push $STABLE
+      # else
+      #   echo " New container failed. Rolling back to stable."
+      #   docker stop nextjs-app || true
+      #   docker rm nextjs-app || true
+      #   docker pull $STABLE
+      #   docker run -d -p 80:3000 --name nextjs-app $STABLE
+      # fi
